### PR TITLE
Added script for publishing appd operator image to DTR

### PR DESCRIPTION
**Pull request by AVINASH793**
Since we don't have any continuous integration and delivery pipeline like Teamcity, so we will set the build tag manually which will be an identifier for images published on Appd DTR and I have selected it in format agentVersion-JIRANumber like 20.12.0-CLUSTERMON2207. Please feel free to make comments.
cc @venkatteki

### CODE REVIEW

**Comment by harekal7** [comment]
Not sure if exposing Jira details would be a good idea

**Comment by venkatteki** [comment]
> Not sure if exposing Jira details would be a good idea

Yes. agreed. we shouldn't include JIRA ticket

**Comment by AVINASH793** [comment]
@venkatteki @harekal7 
Sure. Please suggest unique identifiers because we don't have build number for operator repo and only having agentVersion is not sufficient because there may be more than one image required to publish on DTR for testing purposes in the same month for two different JIRAs.

**Review by venkatteki — COMMENTED** [review]
We shouldn't expose our repo details to outside world

**Pull request closed without merging**
